version: '3'
services:
  dev-env:
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - ../../:/workspaces:cached
    command: sleep infinity
    network_mode: service:dev-db
  dev-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!123
    ports:
      - 1433:1433